### ISSUE TITLE
excel-shared-runtime-scenario cannot be run on Excel Version 2008 (Build 13117.20000) Beta Channel

### ISSUE THREAD

**Issue by chanhohang** [OfficeDev/PnP-OfficeAddins#85] opened 2020-07-27 05:43 UTC
Hello,

My laptop is installed with Office 364 Beta Channel Version 2008 (Build 13117.20000) and when i try to follow the steps in https://github.com/OfficeDev/PnP-OfficeAddins/tree/master/Samples/excel-shared-runtime-scenario

`start npm start`
`npm run sideload`

The sample is not running properly with errors when the excel application starts.
Please find the attached screenshot below. The add-in is not loaded properly.
![github_excel_1](https://user-images.githubusercontent.com/4111001/88507413-b526bd80-d01f-11ea-87d7-9be4e094256a.png)

When the open taskpane is clicked, error message at the status bar saying failed to download resources.
![github_excel_2](https://user-images.githubusercontent.com/4111001/88507416-b657ea80-d01f-11ea-892d-1d907c9e1b14.png)

The excel version is beta channel (insiderfast)
![github_excel_3](https://user-images.githubusercontent.com/4111001/88507417-b657ea80-d01f-11ea-88d3-cf7cb8949fb5.png)

**Comment by davidchesnut** [comment] 2020-10-02 20:58
Hi @chanhohang,  

Sorry for the late reply on this. The shared runtime samples were using an old beta endpoint and we recently updated them for release bits. This may have been the issue you were encountering. If you can try the latest update to the samples that would be great! Please let us know if that doesn't fix the issue.

Thanks!

**Comment by aafvstam** [comment] 2020-10-08 21:33
Tested on 2011 13406.20000, all seems to work properly. I think this can be closed as soon as PR #70 is pushed in ... (probably already works but I tested it at least on the #70 code.

**Comment by aafvstam** [comment] 2020-10-19 21:44
@AlexJerabek @davidchesnut Same here, I'm unable to close the issue (only comment). See above, tested it in my live stream and working so can be closed.

**Comment by davidchesnut** [comment] 2020-10-19 22:21
Hi @aafvstam, (@AlexJerabek as fyi) I just gave you access for issues. We give folks a few days to follow up if they still have questions or the issue isn't resolved. Then a bot will auto-close the issue. So no need to close these.

**Closed** 2020-11-20 04:00 UTC
Labels: Needs: author feedback, Status: fixed, Status: no recent activity, area: excel, bug: sample
