### ISSUE TITLE
Office.ribbon.requestUpdate is throwing exception : The API you are trying to use is not available. It may be available in a different scenario.

### ISSUE THREAD

**Issue by nvazhayil** [OfficeDev/PnP-OfficeAddins#173] opened 2021-06-13 14:05 UTC
**URL of sample**

https://github.com/OfficeDev/PnP-OfficeAddins/tree/main/Samples/office-contextual-tabs

**Describe the bug**

Followed instructions mentioned in https://github.com/OfficeDev/PnP-OfficeAddins/tree/main/Samples/office-contextual-tabs
Loaded the manifest, clicked on "Import Data" and the table showed up. Clicked on the table and the context tab did not show up. Instead there was an error in console saying 

"Uncaught (in promise) RichApi.Error: The API you are trying to use is not available. It may be available in a different scenario.
    at new n (excel-web-16.00.js:formatted:12049)
    at r.i.processRequestExecutorResponseMessage (excel-web-16.00.js:formatted:14829)
    at excel-web-16.00.js:formatted:14754"

This was working earlier and seems to be broken now.

**To Reproduce**

As mentioned above

**Expected behavior**

Context tab should show up.

**Screenshots**

_If applicable, add screenshots to help explain your problem._

**Environment**
- Platform [PC desktop, Mac, iOS, Office Online]: Office Online
- Host [Excel, Word, PowerPoint, etc.]: Excel
- Office version number: ______
- Operating System: Windows 10
- Browser (if using Office Online): Chrome

**Additional context**

This was working till 10th June 2021.

**Comment by AlexJerabek** [comment] 2021-06-14 17:25
Hi @nvazhayil,

Thanks for reporting this. I could not reproduce this issue. It doesn't look like anything in the PNP changed in the last week. Let me assign this to @sohailzafar to investigate from the product side.

**Comment by nvazhayil** [comment] 2021-06-15 03:22
I can reproduce with both the manifest files.

**Comment by Rick-Kirkham** [comment] 2021-06-16 18:50
I'm not able to reproduce this. The sample works as described for me. 
![SnipImage](https://user-images.githubusercontent.com/9088056/122275808-f8d52080-ce98-11eb-8734-5c9627e346e4.JPG)

**Comment by nvazhayil** [comment] 2021-06-16 20:29
It's working for me as well now. Did anything change? what could potentially throw the exception "The API you are trying to use is not available. It may be available in a different scenario."? I used to get this every time in the past few days.

**Comment by Rick-Kirkham** [comment] 2021-06-16 20:41
I can only speculate that some Office online servers had not been updated with the version of Office that recognizes the API, and you were hitting one of them. Otherwise, @sohailzafar may know. 

In the meantime, I'll close this issue.

**Closed by Rick-Kirkham** 2021-06-16 20:41 UTC
Labels: Needs attention :wave:, area: excel, bug: product
